/*--------------------------------------------------------------------------
 * This file is autogenerated during the cmake
 * configuration of your project. If you need to make changes, edit the
 * original file NOT THIS FILE.
 * --------------------------------------------------------------------------*/

#pragma once

#include <string>

#include "H5Support/H5Support.h"

namespace H5Support
{
namespace Version
{
H5Support_EXPORT std::string Complete()
{
  return std::string("1.0.0.0");
}

H5Support_EXPORT std::string Major()
{
  return std::string("1");
}

H5Support_EXPORT std::string Minor()
{
  return std::string("0");
}

H5Support_EXPORT std::string Patch()
{
  return std::string("0");
}

H5Support_EXPORT std::string Revision()
{
  return std::string("0");
}

H5Support_EXPORT std::string Package()
{
  return std::string("1.0.0");
}

H5Support_EXPORT std::string PackageComplete()
{
  return std::string("H5Support Version 1.0.0.0");
}

}; // namespace Version
} // namespace H5Support
